// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ControleEmpresarial.Estoque.IntegrationTest.Alerta.CadastrarAlerta
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CadastrarUmaNovoAlertaFeature : Xunit.IClassFixture<CadastrarUmaNovoAlertaFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CadastrarUmNovoAlerta.feature"
#line hidden
        
        public CadastrarUmaNovoAlertaFeature(CadastrarUmaNovoAlertaFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Cadastrar uma novo alerta", "\tO usuário fará o cadastro de um alerta pelo site\r\n\tpreenchendo os campos necessá" +
                    "rios\r\n\tao terminar receberá uma notificacao \r\n\tde sucesso ou de falha", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastrar alerta com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastrar uma novo alerta")]
        [Xunit.TraitAttribute("Description", "Cadastrar alerta com sucesso")]
        [Xunit.TraitAttribute("Category", "TesteAceitacaoCadastroAlerta")]
        public virtual void CadastrarAlertaComSucesso()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar alerta com sucesso", new string[] {
                        "TesteAceitacaoCadastroAlerta"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("que o usuário está no site, na tela inicial, para cadastrar uma novo alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 11
 testRunner.And("clica na tab Alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 12
 testRunner.And("clica no link Alertas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 13
 testRunner.And("clica no link Novo Alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table1.AddRow(new string[] {
                        "Descricao",
                        "Winchester"});
            table1.AddRow(new string[] {
                        "CondicaoDeAlerta",
                        "1"});
            table1.AddRow(new string[] {
                        "Quantidade",
                        "20"});
            table1.AddRow(new string[] {
                        "cond1",
                        ""});
#line 14
 testRunner.And("preenche os campos com os valores do alerta", ((string)(null)), table1, "E ");
#line 20
 testRunner.When("clicar no botao registrar alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 21
 testRunner.Then("Recebe uma mensagem de cadastro de alerta com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastrar alerta já existente no banco")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastrar uma novo alerta")]
        [Xunit.TraitAttribute("Description", "Cadastrar alerta já existente no banco")]
        public virtual void CadastrarAlertaJaExistenteNoBanco()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar alerta já existente no banco", ((string[])(null)));
#line 23
 this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("que o usuário está no site, na tela inicial, para cadastrar uma novo alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 25
 testRunner.And("clica na tab Alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 26
 testRunner.And("clica no link Alertas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 27
 testRunner.And("clica no link Novo Alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table2.AddRow(new string[] {
                        "Descricao",
                        "Winchester"});
            table2.AddRow(new string[] {
                        "Quantidade",
                        "20"});
#line 28
 testRunner.And("preenche os campos com os valores do alerta", ((string)(null)), table2, "E ");
#line 32
 testRunner.When("clicar no botao registrar alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 33
 testRunner.Then("Recebe uma mensagem de erro pois o alerta já existe no banco", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastrar alerta sem descrição")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastrar uma novo alerta")]
        [Xunit.TraitAttribute("Description", "Cadastrar alerta sem descrição")]
        public virtual void CadastrarAlertaSemDescricao()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar alerta sem descrição", ((string[])(null)));
#line 35
 this.ScenarioSetup(scenarioInfo);
#line 36
 testRunner.Given("que o usuário está no site, na tela inicial, para cadastrar uma novo alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 37
 testRunner.And("clica na tab Alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 38
 testRunner.And("clica no link Alertas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 39
 testRunner.And("clica no link Novo Alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table3.AddRow(new string[] {
                        "Descricao",
                        ""});
            table3.AddRow(new string[] {
                        "Quantidade",
                        "20"});
#line 40
 testRunner.And("preenche os campos com os valores do alerta", ((string)(null)), table3, "E ");
#line 44
 testRunner.When("clicar no botao registrar alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 45
 testRunner.Then("Recebe uma mensagem de erro poiso alerta não possui descrição", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastrar alerta sem quantidade")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastrar uma novo alerta")]
        [Xunit.TraitAttribute("Description", "Cadastrar alerta sem quantidade")]
        public virtual void CadastrarAlertaSemQuantidade()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar alerta sem quantidade", ((string[])(null)));
#line 47
 this.ScenarioSetup(scenarioInfo);
#line 48
 testRunner.Given("que o usuário está no site, na tela inicial, para cadastrar uma novo alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 49
 testRunner.And("clica na tab Alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 50
 testRunner.And("clica no link Alertas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 51
 testRunner.And("clica no link Novo Alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table4.AddRow(new string[] {
                        "Descricao",
                        "Winchester"});
            table4.AddRow(new string[] {
                        "Quantidade",
                        ""});
#line 52
 testRunner.And("preenche os campos com os valores do alerta", ((string)(null)), table4, "E ");
#line 56
 testRunner.When("clicar no botao registrar alerta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 57
 testRunner.Then("Recebe uma mensagem de erro poiso alerta não possui quantidade", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CadastrarUmaNovoAlertaFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CadastrarUmaNovoAlertaFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
